[package]
name = "chive-master"
version = "0.1.0"
edition = "2021"

[package.metadata.cross.build]
default-target = "x86_64-unknown-linux-gnu"
pre-build = [
    "apt-get update && apt-get install build-essential pkg-config libsqlite3-dev libssl-dev libfontconfig-dev -y",
]

[package.metadata.cross.target.x86_64-unknown-linux-gnu]
image = "ubuntu:22.04"

[dependencies]
tokio = { version = "1.35.1", default-features = false, features = [
    "rt-multi-thread",
] }
serenity = { version = "0.11.7", default-features = false, features = [
    "client",
    "gateway",
    "model",
    "rustls_backend",
] }
sqlx = { version = "0.7.3", features = [
    "runtime-tokio-native-tls",
    "sqlite",
    "chrono",
] }
reqwest = { version = "0.11.23", features = ["json"] }
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
rand = "0.8.5"
anyhow = "1.0.79"
dotenv = "0.15.0"
url = "2.5.0"
chrono = "0.4.31"
