name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Get Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install sqlx
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: sqlx-cli

      - name: Prepare sqlx
        run: sqlx db create && sqlx migrate run

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release

      - name: Prepare
        run: mv target/x86_64-unknown-linux-gnu/release/chive-master .

      - name: Delete Old File
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: rm chive-master/chive-master

      - name: Copy New File
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: chive-master
          target: /root/chive-master/

      - name: Restart Service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: systemctl restart chive-master
